version: '2.2'
services:
  backend:
    build: ./backend
    container_name: backend
    image: meder96/picpro:backend
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    ports:
      - "3000:3000"
  frontend:
    build: ./frontend
    container_name: frontend
    image: meder96/picpro:frontend
    ports: 
      - "4200:80"